
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: test-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: joeli2104
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build and push Docker image
        run: |
          docker build -t joeli2104/test:latest .
          docker push joeli2104/test:latest

  deploy:
    name: Deploy to Local Machine (Optional Step)
    runs-on: test-latest
    needs: build  

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Pull and Run Docker Container Locally
        run: |
          # Pull the latest Docker image from DockerHub
          docker pull joeli2104/test:latest

          # Run the Docker container locally
          docker run -d -p 80:80 joeli2104/test:latest