# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: alexismendozaa
          password: ${{ secrets.DOCKER_PASSWORD }}  # Define your Docker Hub password in secrets

      - name: Build and push Docker image
        run: |
          docker build -t alexismendozaa/ubuntu:latest .
          docker push alexismendozaa/ubuntu:latest

  deploy:
    name: Deploy to Local Machine (Optional Step)
    runs-on: ubuntu-latest
    needs: build  # Ensure deployment only occurs after the build job is successful

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Pull and Run Docker Container Locally
        run: |
          # Pull the latest Docker image from DockerHub
          docker pull alexismendozaa/ubuntu:latest

          # Run the Docker container locally
          docker run -d -p 80:80 alexismendozaa/ubuntu:latest